### ISSUE TITLE
Add missing links

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/get.delta.chat#3]

**Comment by ghost** [comment]
We don't have stable portable Windows builds yet, right?

**Comment by ghost** [comment]
Apart from that, I pushed symlinks to download.delta.chat via rsync, totally possible with rssh :) Nice, because we don't need an API :P :D

**Comment by Simon-Laux** [comment]
> We don't have stable portable Windows builds yet, right?

yes, no problem I set it to soon which is hidden
